version: '3'

services:
  opus-mt:
    build: .
    volumes:
      - ./models:/usr/src/app/models
    ports:
      - 8889:80
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

